<?php

return [
    'cleaning' => [
        'name' => 'Cleaning',
        'labels' => [
            'customers' => 'Customers',
            'customer' => 'Customer',
            'sites' => 'Jobs',
            'site' => 'Job',
            'service jobs' => 'Cleaning Checklist',
            'service job' => 'Checklist Item',
            'cleaners' => 'Cleaners',
            'cleaner' => 'Cleaner',
            'attendance' => 'Shift Log',
            'shiftRoster' => 'Availability',
            'role' => 'Role',
            'zone' => 'Team',
            'issues / support' => 'Service Requests',
            'issue / support' => 'Service Request',
            'finance' => 'Money',
            'timeLogs' => 'Time on Job',
            'knowledgebase' => 'Playbooks',
            'service agreements' => 'Service Agreements',
            'team chat' => 'Team Chat',
            'calendar' => 'Schedule & Dispatch',
            'reports' => 'Insights',
            'followup' => 'Follow-Up',
        ],
        'menu' => [
            'primary' => [
                'customers',
                'enquiries',
                'followups',
                'jobs',
                'schedule-dispatch',
                'cleaning-checklist',
                'team',
                'money',
                'service-requests',
                'playbooks',
                'insights',
            ],
        ],
    ],
];
