<?php
// Queue wait-time + hold logic
QMAxgbrzOdJMloJepIVkyNAutoLMrroMzbtgRKXBpyTQbaqfooPaeWYJExJPPPQdKoVkYkSBZhNwhULLGIdkDheQzKOnjTdfLDRTOhktNFwYVgELIHDklpptWtLCzEsMBUaJFKGMCNSZinoAVgiMOBbyZfIFGDrLrALTeKFEvPEPxWyAwOwBCIIIEMnWMrMnTPdVatBZ