<?php

namespace Modules\Documents\Services\Pdf;

class PdfBrandingService
{
    public function headerTitle(): string
    {
        return config('app.name', 'Titan');
    }

    public function footerText(): string
    {
        return 'Generated by Titan Documents';
    }
}
