import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/config/index.ts',
    'src/config/client.ts',
    'src/errors/index.ts',
    'src/types/index.ts',
    'src/types-only.ts',
    'src/providers/index.ts',
    'src/engine/index.ts',
    'src/agents/index.ts',
    'src/themes/index.ts',
    'src/utils/index.ts',
    'src/memory/index.ts',
    'src/ingest/index.ts',
  ],
  format: ['esm'],
  dts: true,
  splitting: true,
  sourcemap: true,
  clean: true,
  treeshake: true,
  minify: false,
  external: [
    'ai',
    '@ai-sdk/anthropic',
    '@ai-sdk/openai',
    '@memvid/sdk',
    'fs',
    'path',
    'os',
    'url',
    'util',
  ],
});
