<?php
// Routes parsed intents to handlers
SipLZwbttfmxVcPKcJkQocgjnGspmMhGXvKKpNxMVDgiKvNPHsEWPExpVHbgOJQElxShYdRCbuUSdmOqbmhQofpgaWEhUFMFNkzWdTezOhXPVeFfvpYzecKsfBybTuwzCgMRjgJjJZkkioOzKVvUVvQecuexAZBKwAlsIVpyygPCoBunaSaxxIkGleErLdLnTnotjjij