<?php
// Call logs table
vNgPVBDOYqlbpzAADDxkEriBerPKdjbzCkpGkGezZdqfzvNRwpyaSigyeSmeFDFvhcgSmNJtcNKevNPYgfrcEdjiHwKMGlfvCddjiqnFaBAEGLfDReDQxexzHChhJVvscMZjRWXkZhQbYzCCOWAsHOrRWVYnSPFzNcOvCTsxZoBlAzOUWqRstLMfTTtAREcBVeRkLQfv