<?php
// Voice command logs table
BXNFzjtCmmAYriWqUEqFtMXvVAGFGYrnhlogcczOGjLrvFBuHasthqQLBFHJSolWceQGCsMUdVxtRpOUqcziyNAmVWfADkuuITLaMWTwCTqELHkqaExrlcWUNepRQfymAFnRLQXlbHXMGuFCLcMakZLgDhSZqUBIJfgwkUUZxLluALOFEDbHXrmrUXPciYDRtjqKyJtr