<?php
// Conversation slot filling + state machine
EEvHtWcQIOUIVhGxeMZPKdTHESBDEOThEgogKBpDlbxHCLSFnwyCEMcozbBdJwSLCajhDEggvbppoLOBmLetETgZneSxGmmUTNCtivtqYyCjgkdMjDfoOwPUOAnKHXHoDShATHmFQPdDiDUhjcRpObYXMxwrhWgGRmSoQcghGhpwEqElxhxtighvroidueAMHTypJjpR