<?php
// Business-hours + IVR routing logic
HAGuZZWGdACPHcMWJrKlrWfzSLaeDAYOCdpiVTHMajsrAcrzypNBpNuvZkglfrVKMDzyQWGigDYKPzZqAXEuOMeDezqXTMLATuMoJtwpUxyXRcPSEcHwMLwgiROtsPmXDYJuiHMCpGENTdIkQQljwwPGyWrEzDTSgwzSXIVyAzCMUuHgMLqXXOLNtnkFRpolgcGhsHZG