CREATE TABLE IF NOT EXISTS tz_signals (
    id VARCHAR(80) PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    team_id BIGINT UNSIGNED NULL,
    user_id BIGINT UNSIGNED NULL,
    process_id VARCHAR(80) NULL,
    type VARCHAR(120) NOT NULL,
    kind VARCHAR(120) NOT NULL,
    severity VARCHAR(20) NOT NULL DEFAULT 'AMBER',
    source VARCHAR(120) NULL,
    origin VARCHAR(120) NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'new',
    validation_result VARCHAR(40) NULL,
    payload JSON NOT NULL,
    meta JSON NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    INDEX idx_tz_signals_company_created (company_id, created_at),
    INDEX idx_tz_signals_company_type (company_id, type, created_at),
    INDEX idx_tz_signals_company_status (company_id, status, created_at),
    INDEX idx_tz_signals_process (process_id)
);
