<?php
// Adds SMS + voice support columns
pnZLWPNLfyvGKLxhDZYvpTBeiiwOLYCBSEhPpWkPnMnUycXiiiOFGGTRievpnpjeFRfRxpSolRyhkodZTspGuToOelYDYyJvWACHHDyyewpgCzJylQUNMQLPGjPaWzNNXQSOaXBcfObcJezvHEvCHElZjEVutOODwHmKvPJTOxIMjuCmfRFmXFLyDAZmibzksMiQYotC