<?php
// Parses transcript into intents/entities
GIqBqpxnDtTobBoYfvWCWMKYMrBCgRmEQjHTCAfSQzdoKHiHGzWDPSEYeICeRQPibtMJMPFejocOwEkANRPbUYSurTTdNttAEWVtazNMRSyoRLhOMkhxSnVXbzRhOFIpixoKmAhxrJwSzFCnzqiLFjcJUriVyKZsHZrgHDvJHgeLtxAWKHeztBoJbeLUvnEWAhcKxEaO